### ISSUE TITLE
Print too many bars cleanly

### ISSUE THREAD

**Issue by Shifulor** [clitic/kdam#3]
Hi again, thanks to your friendly help and elaboration i took a closer look at kdam. Especially bar_multi_thread.rs makes me confident that that kdam is perfect for my needs. However with bar_multi_thread.rs one issue arises:
In the example you specify every bar beforehand with the correct location integer. However i am working in an enviroment where i do not know how many bars there will be, thus i would need something like "append to last bar". Does kdam have such a function or must i try to index each thread? 
Kindest regards

**Comment by clitic** [comment]
There is no such feature as "append to last bar".

You need to create `Arc<Mutex<usize>>` with 0 as default and pass this to each thread. Unwrap this value then set the location and increment it `+1`.

You can also create a `static AtomicUsize`.

**Comment by Shifulor** [comment]
Many thanks, i indexed my tokio threads and kdam worked like a charm, better than indicatif ever could :DD amazing project. However one (quite logical) issue arises: If there are more bars than space availible on the terminal the behaviour becomes quite wierd. I know that this is expected when ~60 bars get started. Should i append you a video so you see what i mean? Its totally okay if you dont care for this huge scalability :D
Many thanks for this great libary

**Comment by clitic** [comment]
You are right it would be not great if 60 bars started at once. For handling such problem tqdm uses `nbars` which stores maximum number of bars to display at once. All rest of bars are hidden if limit exceeds. I would try to implement it in next release.

**Comment by Shifulor** [comment]
Here is an example of where i encounter this issue: https://user-images.githubusercontent.com/83807372/181913603-65d9cf91-0398-4f5c-b221-ab7be76e4784.mp4
If you could implement something like nrows it would be amazing. Maybe delete bars once full starting with bar 1 and going up. This feature would really help me and ofc i would be wiling to try and help you implement it :)

**Comment by clitic** [comment]
tqdm `nrows` like feature couldn't be implemented in rust easily. So I have implemented [kdam::RowManager](https://github.com/clitic/kdam/blob/main/src/manager.rs) as its alternative.

-  Commit cd400989b7de42861a10714849634e6433a651ac
- [Example](https://github.com/clitic/kdam/blob/main/examples/misc_row_manager.rs)

https://user-images.githubusercontent.com/71246790/182090907-b4aa426d-7ebc-43b8-88c9-7d13b2bd214f.mp4

**Comment by Shifulor** [comment]
This looks pretty :D However it does not really solve the problem i had in Mind, maybe make the top bars dissappear one finished? Idk. Anyways many thanks and keep up the amazing work :)

**Comment by clitic** [comment]
@Shifulor try using using `tqdm!(leave = false, ..)`.

**Comment by clitic** [comment]
> This looks pretty :D However it does not really solve the problem i had in Mind, maybe make the top bars dissappear one finished? Idk. Anyways many thanks and keep up the amazing work :)

I think you need something like this. Also `RowManager.append` returns index of append bar which can be used for updating and notifying bars.

[examples/misc_row_manager_leave.rs](https://github.com/clitic/kdam/blob/main/examples/misc_row_manager_leave.rs)

https://user-images.githubusercontent.com/71246790/182198723-cffac4e0-6122-46ed-9566-596eaedb3875.mp4

**Comment by Shifulor** [comment]
That is exactly what i was looking for :D awesome! I will implement that asap. Thanks for that great work!! Oh just one minor thing if you have spare time: a feature like RowManager::new(auto) that automatically checks how many rows fit into the current terminal would be handy.

**Comment by clitic** [comment]
It's already implemented use `kdam::RowManager::from_window_size()`.

**Comment by Shifulor** [comment]
Again: AMAZING. However sadly after trying to implement row manager i found an issue that prevents me from implementing it :skull: . I cannot append to the main Rowmanager struct from within a tokio thread and i cannot add the tqdm! items before entering the threads. I know that this is not in any way your fault tho so you cant change that :) Have a great day

**Comment by clitic** [comment]
You can try to append afterwards in that specific Tokio thread.

Some pseudo code.

```
manager = Arc<Mutex<BarManager>>

tokio thread spwan
  let m = manager.lock().unwrap();
  let index = manager.append(tqdm!());
  drop(m);

  do work

  let m = manager.lock().unwrap();
  m.get_mut(index).unwrap().update(1);
  m.notify(index);
```

**Comment by Shifulor** [comment]
Thanks for you ideas, sadly i cannot access the external manager variable in the tokio thread. However i have another idea: can i do something like `manager.get_mut(1).update_total` ? I couldnt find something like that in the docs.
Because technically i could know how many tqdm's i will need before starting the threads and append the total variable to them in the individual threads. Many thanks for your kind help

**Comment by clitic** [comment]
You can use this `manager.get_mut(1).reset(Some(total))` to update total value later on.

**Comment by Shifulor** [comment]
Okay so i did this https://hastebin.skyra.pw/pehawovaha.rust but it seems that tokio and RowManager just arent friends: One bar gets printed and the rest just stays black. idk. Do you see something i did wrong? else ill just use the old tqdm! variant :)

**Comment by clitic** [comment]
You are locking manager at line 29. Thats why all other can't access manager and only one bar shows up. You should lock after 56th line (inside while loop).

Also in line 10 you should use `leave = false` for your desired output.

If this even doesn't work then try to use `kdam::RowManager::new(5)`

**Comment by Shifulor** [comment]
Many thanks, i forgot to drop the manager now everything works great and looks amazing. I will make sure to spread the word of this great progress bar!
